#!/bin/sh

K_SYS="$1"
echo "System name: $K_SYS"

if [ -z "$PT_HOST" ]; then
  echo "\$PT_HOST is empty"
  exit 1
fi

if [ -z "$PT_PORT" ]; then
  echo "\$PT_PORT is empty"
  exit 1
fi

/kail --current-ns 2>&1 | logger -n "$PT_HOST" -P "$PT_PORT" -t "$K_SYS" 