#!/bin/sh

K_SYS="$1"
echo "System name: $K_SYS"

rm -f /"$K_SYS"
touch /"$K_SYS"
/remote_syslog -p "$PT_PORT" -d "$PT_HOST" --hostname "$K_SYS" --pid-file=/remote_syslog.pid /"$K_SYS"
/kail --log-file /"$K_SYS" --current-ns > /"$K_SYS" 2>&1