#!/bin/sh

K_SYS="$1"

if [ -z "$K_SYS" ]; then
  echo "System tag is empty"
  exit 1
fi

echo "System name: $K_SYS"

if [ -z "$PT_HOST" ]; then
  echo "\$PT_HOST is empty"
  exit 1
fi

if [ -z "$PT_PORT" ]; then
  echo "\$PT_PORT is empty"
  exit 1
fi

/kail 2>&1 | logger -n "$PT_HOST" -P "$PT_PORT" -t "$K_SYS" 